/* eslint-disable */
// Do not edit this file, it is auto-generated at build time!
// See scripts/generate-component-factory.js to modify the generation of this file.
import ContentBlock from './ContentBlock';
import StyleguideComponentParams from './Styleguide-ComponentParams';
import StyleguideCustomRouteType from './Styleguide-CustomRouteType';
import StyleguideFieldUsageCheckbox from './Styleguide-FieldUsage-Checkbox';
import StyleguideFieldUsageContentList from './Styleguide-FieldUsage-ContentList';
import StyleguideFieldUsageCustom from './Styleguide-FieldUsage-Custom';
import StyleguideFieldUsageDate from './Styleguide-FieldUsage-Date';
import StyleguideFieldUsageFile from './Styleguide-FieldUsage-File';
import StyleguideFieldUsageImage from './Styleguide-FieldUsage-Image';
import StyleguideFieldUsageItemLink from './Styleguide-FieldUsage-ItemLink';
import StyleguideFieldUsageLink from './Styleguide-FieldUsage-Link';
import StyleguideFieldUsageNumber from './Styleguide-FieldUsage-Number';
import StyleguideFieldUsageRichText from './Styleguide-FieldUsage-RichText';
import StyleguideFieldUsageText from './Styleguide-FieldUsage-Text';
import StyleguideLayout from './Styleguide-Layout';
import StyleguideLayoutReuse from './Styleguide-Layout-Reuse';
// import StyleguideLayoutTabs from './Styleguide-Layout-Tabs';
// import StyleguideLayoutTabsTab from './Styleguide-Layout-Tabs-Tab';
import StyleguideMultilingual from './Styleguide-Multilingual';
import StyleguideRouteFields from './Styleguide-RouteFields';
import StyleguideSection from './Styleguide-Section';
import StyleguideSitecoreContext from './Styleguide-SitecoreContext';

const components = new Map();
components.set('ContentBlock', ContentBlock);
components.set('Styleguide-ComponentParams', StyleguideComponentParams);
components.set('Styleguide-CustomRouteType', StyleguideCustomRouteType);
components.set('Styleguide-FieldUsage-Checkbox', StyleguideFieldUsageCheckbox);
components.set('Styleguide-FieldUsage-ContentList', StyleguideFieldUsageContentList);
components.set('Styleguide-FieldUsage-Custom', StyleguideFieldUsageCustom);
components.set('Styleguide-FieldUsage-Date', StyleguideFieldUsageDate);
components.set('Styleguide-FieldUsage-File', StyleguideFieldUsageFile);
components.set('Styleguide-FieldUsage-Image', StyleguideFieldUsageImage);
components.set('Styleguide-FieldUsage-ItemLink', StyleguideFieldUsageItemLink);
components.set('Styleguide-FieldUsage-Link', StyleguideFieldUsageLink);
components.set('Styleguide-FieldUsage-Number', StyleguideFieldUsageNumber);
components.set('Styleguide-FieldUsage-RichText', StyleguideFieldUsageRichText);
components.set('Styleguide-FieldUsage-Text', StyleguideFieldUsageText);
components.set('Styleguide-Layout', StyleguideLayout);
components.set('Styleguide-Layout-Reuse', StyleguideLayoutReuse);
// components.set('Styleguide-Layout-Tabs', StyleguideLayoutTabs);
// components.set('Styleguide-Layout-Tabs-Tab', StyleguideLayoutTabsTab);
components.set('Styleguide-Multilingual', StyleguideMultilingual);
components.set('Styleguide-RouteFields', StyleguideRouteFields);
components.set('Styleguide-Section', StyleguideSection);
components.set('Styleguide-SitecoreContext', StyleguideSitecoreContext);

export default function componentFactory(componentName) {
  return components.get(componentName);
};
